- name: install zabbix-agent repository
  shell: rpm -i https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-1.el7.noarch.rpm
- name: install zabbix-agent
  yum: name=zabbix-agent
- name: setup zabbix-agent conf
  template: src=zabbix_agentd.conf dest=/etc/zabbix/zabbix_agentd.conf
- name: start zabbix-agent
  service: name=zabbix-agent state=started
- name: add service when power on
  shell: systemctl enable zabbix-agent